apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose-produse.yml
    kompose.version: 1.24.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f docker-compose-produse.yml
        kompose.version: 1.24.0 ()
      creationTimestamp: null
      labels:
        io.kompose.network/pipeline-network: "true"
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: MAGICBEAN_VERSION
              value: 2.7.6
            - name: MB_CORS_ALLOWED_ORIGINS
              value: http://localhost:9010
            - name: MB_HIVE_THRIFT_PASSWORD
              value: "123456"
            - name: MB_HIVE_THRIFT_USERNAME
              value: postgres
            - name: MB_POSTGRES_PWD
              value: "123456"
            - name: MB_POSTGRES_USER
              value: postgres
          image: hykpi/hykpi_backend:2.7.6
          name: backend
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
