apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose-produse.yml
    kompose.version: 1.24.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: hykpi-hive-db
  name: hykpi-hive-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hykpi-hive-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f docker-compose-produse.yml
        kompose.version: 1.24.0 ()
      creationTimestamp: null
      labels:
        io.kompose.network/pipeline-network: "true"
        io.kompose.service: hykpi-hive-db
    spec:
      containers:
        - args:
            - postgres
            - -c
            - listen_addresses=*
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data
            - name: POSTGRES_DB
              value: modou_hive
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: POSTGRES_USER
              value: postgres
          image: hykpi/hykpi_hive_db:2.6.0
          name: hykpi_hive_db
          resources: {}
      restartPolicy: Always
status: {}
