apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose-produse.yml
    kompose.version: 1.24.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: pipeline
  name: pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pipeline
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f docker-compose-produse.yml
        kompose.version: 1.24.0 ()
      creationTimestamp: null
      labels:
        io.kompose.network/pipeline-network: "true"
        io.kompose.service: pipeline
    spec:
      containers:
        - env:
            - name: MAGICBEAN_VERSION
              value: 2.7.6
            - name: MODOU_HIVE_PASSWORD
              value: "123456"
            - name: MODOU_HIVE_USER
              value: postgres
          image: hykpi/hykpi_pipeline:2.7.6
          name: pipeline
          resources: {}
          volumeMounts:
            - mountPath: /modou/workspace
              name: pipeline-claim0
      restartPolicy: Always
      volumes:
        - name: pipeline-claim0
          persistentVolumeClaim:
            claimName: pipeline-claim0
status: {}
